language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t jamesn8docker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jamesn8docker/react-test npm test

after_success:
  - docker build -t jamesn8docker/multi-client ./client
  - docker build -t jamesn8docker/multi-nginx ./nginx
  - docker build -t jamesn8docker/multi-server ./server
  - docker build -t jamesn8docker/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push them to DockerHub
  - docker push jamesn8docker/multi-client
  - docker push jamesn8docker/multi-nginx
  - docker push jamesn8docker/multi-server
  - docker push jamesn8docker/multi-worker

#deploy:
#  provider: elasticbeanstalk
#  region: "us-west-2"
#  app: "docker-react"
#  env: "DockerReact-env"
#  bucket_name: "elasticbeanstalk-us-west-2-221279602931"
#  bucket_path: "docker-react"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY